name: Deployment

concurrency: production

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deployment:
    runs-on: ubuntu-lates
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: deploy
      run: cargo build --verbose --release
